name: Publish

on:
  push:
#    paths:
#      - 'yyxx_game_pkg/**'
    branches:
      - master

    tags:
      - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '[BUILD]') ||
      startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip poetry toml

      - name: Modify toml Set Version
        run: python gen_version.py

      - name: Build dist
        run: poetry build --no-interaction
        
      - name: Publish a Python distribution to PyPI
        run: poetry publish yyxx-gitlab

